// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lozhxacampqoxmjbnekf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvemh4YWNhbXBxb3htamJuZWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTQ1NjIsImV4cCI6MjA2OTYzMDU2Mn0.qKpRbXEFQyRZW4Zj1XiUkNHLdxEqK99iBkfGGEBeZFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});